openapi: 3.0.0
info:
  title: 세상의 모든 칵테일 COKTAIL
  url: http://kdt-sw-7-team07.elicecoding.com
  description: COK API 문서
  version: 1.0.0
  contact:
    name: COK 공식 사이트
    email: seodnjstlr@gmail.com
    url: http://kdt-sw-7-team07.elicecoding.com
externalDocs:
  description: COK 개발팀 관련 정보
  url: https://kdt-gitlab.elice.io/sw_track/class_07/web_project_2/team7
servers:
  - url: http://kdt-sw-7-team07.elicecoding.com:3000/api/v1
    description: COK API 서버
  - url: http://localhost:3000/api/v1
    description: 로컬 API 서버
tags:
  - name: KaKao
    description: 카카오 소셜 로그인을 통한 사용자 인증 및 관리
  - name: Search
    description: 술, 칵테일, 술집 등에 대한 검색 기능
  - name: Bars
    description: 지도를 통한 술집에 대한 정보
  - name: Bases
    description: 칵테일에 들어가는 기본 술에 대한 정보
  - name: Cocktails
    description: 다양한 칵테일 레시피 및 제조 방법에 대한 정보
  - name: DiyRecipes
    description: 사용자가 직접 만들고, 술 레시피 및 제조 방법에 대한 정보 공유
  - name: Reviews
    description: 사용자들이 남긴 DIY레시피, 칵테일에 대한 리뷰
  - name: Users
    description: 사용자 계정 관리
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: JwtToken
  schemas:
    Bar:
      type: object
      required:
        - name
        - address
        - time
      properties:
        name:
          type: string
          description: 바 이름
        image:
          type: string
          description: 바 이미지
        address:
          type: string
          description: 바 주소
        tel:
          type: string
          description: 바 전화번호(핸드폰)
        time:
          type: string
          description: 운영 시간 
        x:
          type: number
          description: 경도
        y:
          type: number
          description: 위도

    Base:
      type: object
      required:
        - name
        - image
      properties:
        name:
          type: string
          description: 베이스 술 이름
        image:
          type: string
          description: 베이스 술 이미지
    User:
      type: object
      required:
        - email
      properties:
        kakaoId:
          type: number
          unique: true
          description: 카카오ID 번호
        email:
          type: string
          required: true
          unique: true
          description: 이메일
        image:
          type: string
          description: 프로필 이미지
        nickname:
          type: string
          description: 닉네임
        custom:
          description: 설문조사 결과 저장
          type: object
          properties:
            base:
              type: string
              description: 베이스 술
            abv:
              type: number
              description: 도수
            sweet:
              type: number
              description: 단맛
            sour:
              type: number
              description: 신맛
            bitter:
              type: number
              description: 쓴맛
        wishes:
          description: 찜 목록
          cocktails:
            type: mongoose.Schema.Types.ObjectId
            ref: 'Cocktail'
            description: 칵테일 MongoDB ID
          diyRecipes:
            type: mongoose.Schema.Types.ObjectId
            ref: 'DiyRecipe'
            description: DIY 레시피 MongoDB ID
        isAdmin:
          type: Boolean
          default: false
          description: 관리자 여부
        isWrite:
          type: Boolean
          default: true
          description: 글쓰기 권한 여부
        deletedAt:
          type: Date
          default: null
          description: 유저 삭제 여부(실제 삭제는 관리자만 가능)
    Cocktail:
      type: object
      required:
        - name
        - base
        - ingredient
        - abv
        - sweet
        - bitter
        - sour
      properties:
        name:
          type: string
          example: 데킬라
          description: 칵테일 이름
        base:
          type: mongoose.Schema.Types.ObjectId
          ref: 'Base'
          example: 657c40723d11af1efa276da5
          description: 베이스 MongoDB ID
        image:
          type: string
          example: /images/1703335017251.png
          description: 칵테일 이미지
        description:
          type: string
          example: 프레시한 라임의 향과 테킬라의 깊은 맛이 어우러진 칵테일
          description: 칵테일 설명
        ingredient:
          type: string
          example: 테킬라, 라임 주스, 오렌지 리큐어
          description: 칵테일 재료
        tags:
          description: 태그
          type: string
          example:
            - 프레시
            - 라임
        recipes:
          description: 제조 방법
          type: Array
            - image:
              type: string
              example: /images/margarita_step1.jpg
            content:
              type: string
              example: 모든 재료를 셰이커에 넣습니다
        abv:
          type: integer
          min: 1
          max: 5
          description: 도수 
        sweet:
          type: integer
          min: 1
          max: 5
          description: 단맛
        bitter:
          type: integer
          min: 1
          max: 5
          description: 쓴맛
        sour:
          type: integer
          min: 1
          max: 5
          description: 신맛
        reviews:
          type: mongoose.Schema.Types.ObjectId
          ref: 'CocktailReview'
          description: 칵테일 리뷰 MongoDB ID
        wishes:
          type: mongoose.Schema.Types.ObjectId
          ref: 'User'
          description: 칵테일 찜 목록 유저 MongoDB ID
        avgRating:
          type: number
          default: 0
          example: 4
          description: 평균 별점
        reviewCount:
          type: integer
          default: 0
          example: 4
          description: 리뷰 숫자
    DiyRecipe:
      type: object
      required:
        - name
        - base
        - ingredient
        - abv
        - sweet
        - bitter
        - sour
      properties:
        name:
          type: string
          example: 데킬라
          description: 칵테일 이름
        base:
          type: mongoose.Schema.Types.ObjectId
          ref: 'Base'
          example: 657c40723d11af1efa276da5
          description: 베이스 MongoDB ID
        image:
          type: string
          example: /images/1703335017251.png
          description: 칵테일 이미지
        description:
          type: string
          example: 프레시한 라임의 향과 테킬라의 깊은 맛이 어우러진 칵테일
          description: 칵테일 설명
        ingredient:
          type: string
          example: 테킬라, 라임 주스, 오렌지 리큐어
          description: 칵테일 재료
        tags:
          description: 태그
          type: string
          example:
            - 프레시
            - 라임
        recipes:
          description: 제조 방법
          type: Array
            - image:
                type: string
                example: /images/margarita_step1.jpg
              content:
                type: string
                example: 모든 재료를 셰이커에 넣습니다
        abv:
          type: integer
          min: 1
          max: 5
          description: 도수
        sweet:
          type: integer
          min: 1
          max: 5
          description: 단맛
        bitter:
          type: integer
          min: 1
          max: 5
          description: 쓴맛
        sour:
          type: integer
          min: 1
          max: 5
          description: 신맛
        reviews:
          type: mongoose.Schema.Types.ObjectId
          ref: 'DiyRecipeReview'
          description: DIY레시피 리뷰 MongoDB ID
        wishes:
          type: mongoose.Schema.Types.ObjectId
          ref: 'User'
          description: DIY레시피 찜 목록 유저 MongoDB ID
        avgRating:
          type: number
          default: 0
          example: 4
          description: 평균 별점
        reviewCount:
          type: integer
          default: 0
          example: 4
          description: 리뷰 숫자
    CocktailReview:
      type: object
      required:
        - user
        - cocktail
        - content
        - rating
      properties:
        user: 
          type: mongoose.Schema.Types.ObjectId
          ref: 'User'
          example: 658483ca8c493751548540cb
          description: 리뷰 작성자
        cocktail: 
          type: mongoose.Schema.Types.ObjectId
          ref: 'Cocktail'
          example: 657a6d3613c09f7d6b5f8819
          description: 칵테일
        content: 
          type: string
          example: 이거 클스마스때 해서 드셔보세묭 아주 좋아요
          description: 리뷰 내용
        images: 
          type: string
          description: 리뷰 이미지
          example:
            - aaa.png
            - bbb.png
        rating: 
          type: integer
          required: true
          description: 별점
          example: 5
        likes: 
          description: 좋아요
          type: Array
            - type: mongoose.Schema.Types.ObjectId
              ref: 'User'
              required: true
          example:
            - 658483ca8c493751548540cb
    DiyRecipeReview:
      type: object
      required:
        - user
        - cocktail
        - content
        - rating
      properties:
        user: 
          type: mongoose.Schema.Types.ObjectId
          ref: 'User'
          example: 658483ca8c493751548540cb
          description: 리뷰 작성자
        cocktail: 
          type: mongoose.Schema.Types.ObjectId
          ref: 'DiyRecipe'
          example: 657a6d3613c09f7d6b5f8819
          description: 칵테일
        content: 
          type: string
          example: 이거 클스마스때 해서 드셔보세묭 아주 좋아요
          description: 리뷰 내용
        images: 
          type: string
          description: 리뷰 이미지
          example:
            - aaa.png
            - bbb.png
        rating: 
          type: integer
          required: true
          description: 별점
          example: 5
        likes: 
          description: 좋아요
          type: Array
            - type: mongoose.Schema.Types.ObjectId
              ref: 'User'
              required: true
          example:
            - 658483ca8c493751548540cb

paths:
  /auth/kakao:
    get:
      tags:
        - KaKao
      summary: 카카오 로그인
      security:
        - oauthScheme: []
      responses:
        '201':
          description: 쿠키에 jwtToken
          content:
            application/json:
              schema:
                type: object
                properties:
                  jwtToken:
                    type: string
        '500':
          description: 서버 오류 입니다.
  /auth/kakao/withdrawal:
    delete:
      tags:
        - KaKao
      summary: 카카오 연결 해제-탈퇴
      security:
        - jwtToken: []
      parameters:
        - name: jwtToken
          in: cookie
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 카카오 연결 해제와 동시에 탈퇴, 토큰 삭제
        '500':
          description: 서버 오류 입니다.

  /users:
    get:
      tags:
        - Users
      summary: 사용자 목록 조회(관리자)
      security:
        - cookieAuth: []
      parameters:
        - name: perPage
          in: query
          schema:
            type: number
        - name: page
          in: query
          schema:
            type: number
      responses:
        '200':
          description: 사용자 목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  nickname:
                    type: string
                  isWrite:
                    type: boolean
                  createAt:
                    type: string
                    format: date
                  updatedAt:
                    type: string
                    format: date
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류
        '403':
          description: 접근 제한    	
        '500':
          description: 서버 오류                    
  /users/:id/permissions:
    put:
      tags:
        - Users
      summary: 글쓰기, 리뷰 쓰기 권한 수정(관리자)
      security:
        - cookieAuth: []
      parameters:
        - name: jwtToken
          in: cookie
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 권한 수정 성공
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류
        '403':
          description: 접근 제한    	
        '404':
          description: 요청한 리소스 찾을 수 없음
        '409':
          description: 중복 오류
        '500':
          description: 서버 오류          

  /users/:id/delete:
    delete:
      tags:
        - Users
      summary: 사용자 삭제(관리자)
      security:
        - cookieAuth: []
      parameters:
        - name: jwtToken
          in: cookie
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 사용자 삭제 성공
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류
        '403':
          description: 접근 제한    	
        '404':
          description: 요청한 리소스 찾을 수 없음
        '500':
          description: 서버 오류          
  /user/custom:
    put:
      tags:
        - Users
      summary: 사용자 커스텀 설정
      security:
        - cookieAuth: []
      parameters:
        - name: jwtToken
          in: cookie
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 사용자 커스텀 설정 성공
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류	
        '404':
          description: 요청한 리소스 찾을 수 없음
        '500':
          description: 서버 오류          
  /users/mypage:
    get:
      tags:
        - Users
      summary: 사용자 정보 조회
      security:
        - cookieAuth: []
      parameters:
        - name: jwtToken
          in: cookie
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 사용자 정보 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  email:
                    type: string
                  nickname:
                    type: string
                  createdAt:
                    type: string
                    format: date
                  updatedAt:
                    type: string
                    format: date
        '401':
          description: 인증 오류   	
        '404':
          description: 요청한 리소스 찾을 수 없음
        '500':
          description: 서버 오류                    
    put:
      tags:
        - Users
      summary: 사용자 정보 수정
      security:
        - cookieAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                name:
                  type: string
      responses:
        '200':
          description: 사용자 정보 수정 성공
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류
        '404':
          description: 요청한 리소스 찾을 수 없음
        '409':
          description: 중복 오류
        '500':
          description: 서버 오류    
  /users/logout:
    delete:
      tags:
        - Users
      summary: 사용자 로그 아웃
      security:
        - cookieAuth: []
      responses:
        '204':
          description: 사용자 로그 아웃 성공    	
        '500':
          description: 서버 오류          
  /users/wishlist:
    get:
      tags:
        - Users
      summary: 사용자 찜목록 조회
      security:
        - cookieAuth: []
      parameters:
        - name: type
          in: query
          schema:
            type: string
            enum: [cocktails, recipes]
        - name: cursorId
          in: query
          schema:
            type: string
        - name: perPage
          in: query
          schema:
            type: number
        - name: page
          in: query
          schema:
            type: number
      responses:
        '200':
          description: 사용자 찜목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  name:
                    type: string
                  image:
                    type: string
                  avgRating:
                    type: string
                  reviewCount:
                    type: string
                  createdAt:
                    type: string
                    format: date
                  updatedAt:
                    type: string
                    format: date
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류  	
        '500':
          description: 서버 오류                 
  /users/wishlist/:id:
    post:
      tags:
        - Users
      summary: 사용자 찜 추가
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: 사용자 찜 추가 성공
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류	
        '404':
          description: 요청한 리소스 찾을 수 없음
        '409':
          description: 중복 오류
        '500':
          description: 서버 오류     
    delete:
      tags:
        - Users
      summary: 사용자 찜 삭제
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 사용자 찜 삭제 성공
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류 	
        '404':
          description: 요청한 리소스 찾을 수 없음
        '500':
          description: 서버 오류      
  /users/login:
    post:
      tags:
        - Users
      summary: 테스트용 로그인
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  example: admin
                pw:
                  type: string
                  example: admin
      responses:
        '201':
          description: 로그인 성공
        '400':
          description: 입력 데이터 오류 	
        '404':
          description: 요청한 리소스 찾을 수 없음
        '500':
          description: 서버 오류        

  /bases:
    get:
      tags:
        - Bases
      summary: 베이스 목록 조회
      responses:
        '200':
          description: 베이스 목록 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    name:
                      type: string
                    images:
                      type: string
        '500':
          description: 서버 오류                      
    post:
      tags:
        - Bases
      summary: 베이스 등록
      security:
        - cookieAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                newImageNames:
                  type: string
      responses:
        '201':
          description: 베이스 등록 성공
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류
        '403':
          description: 접근 제한    	
        '409':
          description: 중복 오류
        '500':
          description: 서버 오류
  /bases/:id:
    get:
      tags:
        - Bases
      summary: 베이스 상세 조회
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 베이스 상세 조회 성공
        '400':
          description: 입력 데이터 오류  	
        '404':
          description: 요청한 리소스 찾을 수 없음
        '500':
          description: 서버 오류      
        
    delete:
      tags:
        - Bases
      summary: 베이스 삭제
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 베이스 삭제 성공
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류
        '403':
          description: 접근 제한    	
        '404':
          description: 요청한 리소스 찾을 수 없음
        '500':
          description: 서버 오류       
    put:
      tags:
        - Bases
      summary: 베이스 수정
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                newImageNames:
                  type: string
      responses:
        '200':
          description: 베이스 수정 성공
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류
        '403':
          description: 접근 제한    	
        '404':
          description: 요청한 리소스 찾을 수 없음
        '409':
          description: 중복 오류
        '500':
          description: 서버 오류        

  /cocktails/custom:
    get:
      tags:
        - Cocktails
      summary: 개인 맞춤 추천 칵테일 조회(회원)
      security:
        - cookieAuth: []
      responses:
        '200':
          description: 개인 맞춤 추천 칵테일 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  name:
                    type: string
                  images:
                    type: string
                  abv:
                    type: number
                  sweet:
                    type: number
                  bitter:
                    type: number
                  sour:
                    type: number
                  reviewCount:
                    type: number
                  wishCount:
                    type: number
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류  	
        '404':
          description: 요청한 리소스 찾을 수 없음
        '500':
          description: 서버 오류              
  /cocktails:
    get:
      tags:
        - Cocktails
      summary: 칵테일 목록 조회/정렬기능
      parameters:
        - name: base
          in: query
          schema:
            type: string
        - name: sort
          in: query
          schema:
            type: string
            enum: [review, rating]
        - name: abv
          in: query
          schema:
            type: number
        - name: sweet
          in: query
          schema:
            type: number
        - name: bitter
          in: query
          schema:
            type: number
        - name: sour
          in: query
          schema:
            type: number
        - name: page
          in: query
          schema:
            type: number
        - name: perPage
          in: query
          schema:
            type: number
        - name: cursorId
          in: query
          schema:
            type: string
        - name: cursorValue
          in: query
          schema:
            type: number
      responses:
        '200':
          description: 칵테일 목록 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    name:
                      type: string
                    image:
                      type: string
                    avgRating:
                      type: number
                    reviewCount:
                      type: string
        '400':
          description: 입력 데이터 오류 	
        '500':
          description: 서버 오류                   
    post:
      tags:
        - Cocktails
      summary: 칵테일 등록
      security:
        - cookieAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                newImageNames:
                  type: string
                recipeImageNames:
                  type: string
                description:
                  type: string
                ingredient:
                  type: string
                content:
                  type: string
                abv:
                  type: number
                sweet:
                  type: number
                bitter:
                  type: number
                sour:
                  type: number
      responses:
        '201':
          description: 칵테일 등록 성공
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류
        '403':
          description: 접근 제한    	
        '409':
          description: 중복 오류
        '500':
          description: 서버 오류
  /cocktails/:id:
    get:
      tags:
        - Cocktails
      summary: 칵테일 정보 조회
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 칵테일 정보 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  name:
                    type: string
                  images:
                    type: string
                  tag:
                    type: string
                  description:
                    type: string
                  ingredient:
                    type: string
                  recipe:
                    type: string
                  abv:
                    type: number
                  sweet:
                    type: number
                  bitter:
                    type: number
                  sour:
                    type: number
                  review:
                    type: array
                    items:
                      type: string
                  reviewCount:
                    type: number
                  avgRating:
                    type: number
        '400':
          description: 입력 데이터 오류 	
        '404':
          description: 요청한 리소스 찾을 수 없음
        '500':
          description: 서버 오류                    
    put:
      tags:
        - Cocktails
      summary: 칵테일 수정
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                newImageNames:
                  type: string
                recipeImageNames:
                  type: string
                description:
                  type: string
                ingredient:
                  type: string
                content:
                  type: string
                abv:
                  type: number
                sweet:
                  type: number
                bitter:
                  type: number
                sour:
                  type: number
      responses:
        '200':
          description: 칵테일 수정 성공
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류
        '403':
          description: 접근 제한    	
        '404':
          description: 요청한 리소스 찾을 수 없음
        '409':
          description: 중복 오류
        '500':
          description: 서버 오류          
    delete:
      tags:
        - Cocktails
      summary: 칵테일 삭제
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 칵테일 삭제 성공
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류
        '403':
          description: 접근 제한    	
        '404':
          description: 요청한 리소스 찾을 수 없음
        '500':
          description: 서버 오류          
  /diy-recipes:
    get:
      tags:
        - DiyRecipes
      summary: 레시피 목록 조회
      parameters:
        - name: base
          in: query
          schema:
            type: string
        - name: sort
          in: query
          schema:
            type: string
            enum: [review, rating]
        - name: abv
          in: query
          schema:
            type: number
        - name: sweet
          in: query
          schema:
            type: number
        - name: bitter
          in: query
          schema:
            type: number
        - name: sour
          in: query
          schema:
            type: number
        - name: page
          in: query
          schema:
            type: number
        - name: perPage
          in: query
          schema:
            type: number
        - name: cursorId
          in: query
          schema:
            type: string
        - name: cursorValue
          in: query
          schema:
            type: number
      responses:
        '200':
          description: 레시피 목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  diyRecipesSize:
                    type: number
                  diyRecipes:
                    type: array
                    items:
                      type: object
                      properties:
                        list:
                          type: array
                          items:
                            type: object
                            properties:
                              _id:
                                type: string
                              name:
                                type: string
                              images:
                                type: array
                                items:
                                  type: string
                              reviewCount:
                                type: number
                              likeCount:
                                type: number
                              avgRating:
                                type: number
                        date:
                          type: string
                          format: date
        '400':
          description: 입력 데이터 오류	
        '500':
          description: 서버 오류                          
    post:
      tags:
        - DiyRecipes
      summary: 레시피 생성
      security:
        - cookieAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                newImageNames:
                  type: string
                recipeImageNames:
                  type: string
                description:
                  type: string
                ingredient:
                  type: string
                content:
                  type: string
                abv:
                  type: number
                sweet:
                  type: number
                bitter:
                  type: number
                sour:
                  type: number
      responses:
        '201':
          description: 레시피 생성 성공
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류 	
        '409':
          description: 중복 오류
        '500':
          description: 서버 오류          
  /diy-recipes/users:
    get:
      tags:
        - DiyRecipes
      summary: 사용자의 레시피 목록 조회
      security:
        - cookieAuth: []
      parameters:
        - name: perPage
          in: query
          schema:
            type: number
        - name: cursorId
          in: query
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: number
      responses:
        '200':
          description: 사용자의 레시피 목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  name:
                    type: string
                  image:
                    type: string
                  reviewCount:
                    type: number
                  likeCount:
                    type: number
                  avgrating:
                    type: number
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류   	
        '500':
          description: 서버 오류                    
  /diy-recipes/:id:
    get:
      tags:
        - DiyRecipes
      summary: 레시피 정보 조회
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 레시피 정보 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  user:
                    type: string
                  name:
                    type: string
                  images:
                    type: string
                  description:
                    type: string
                  ingredient:
                    type: string
                  recipe:
                    type: string
                  abv:
                    type: number
                  sweet:
                    type: number
                  bitter:
                    type: number
                  sour:
                    type: number
                  review:
                    type: array
                    items:
                      type: string
                  reviewCount:
                    type: number
                  likeCount:
                    type: number
                  avgRating:
                    type: number
        '400':
          description: 입력 데이터 오류  	
        '404':
          description: 요청한 리소스 찾을 수 없음
        '500':
          description: 서버 오류                    
    put:
      tags:
        - DiyRecipes
      summary: 레시피 수정
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                newImageNames:
                  type: string
                recipeImageNames:
                  type: string
                description:
                  type: string
                ingredient:
                  type: string
                content:
                  type: string
                abv:
                  type: number
                sweet:
                  type: number
                bitter:
                  type: number
                sour:
                  type: number
      responses:
        '200':
          description: 레시피 수정 성공
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류
        '403':
          description: 접근 제한    	
        '404':
          description: 요청한 리소스 찾을 수 없음
        '409':
          description: 중복 오류
        '500':
          description: 서버 오류          
    delete:
      tags:
        - DiyRecipes
      summary: 레시피 삭제
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 레시피 삭제 성공
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류
        '403':
          description: 접근 제한    	
        '404':
          description: 요청한 리소스 찾을 수 없음
        '500':
          description: 서버 오류          
  /bars:
    get:
      tags:
        - Bars
      summary: 지도에서 바 목록 조회
      parameters:
        - name: x1
          in: query
          schema:
            type: number
            example: 0
        - name: x2
          in: query
          schema:
            type: number
            example: 200
        - name: y1
          in: query
          schema:
            type: number
            example: 0
        - name: y2
          in: query
          schema:
            type: number
            example: 200
        - name: keyword
          in: query
          schema:
            type: string
          example: 바
        - name: perPage
          in: query
          schema:
            type: number
            example: 2
        - name: page
          in: query
          schema:
            type: number
            example: 1
      responses:
        '200':
          description: 지도에서 바 목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  name:
                    type: string
                  image:
                    type: string
                  address:
                    type: string
                  tel:
                    type: string
                  time:
                    type: string
                  x:
                    type: number
                  y:
                    type: number
                example:
                  total: 1
                  bars:
                    - _id: 658168a64b2f58b3b093d737
                      name: 원식바1
                      image: MSG_8031703352165894.png
                      address: 서울특별시 강남구1
                      tel: 02-1234-5678
                      time: 18:00 - 02:00
                      x: 127
                      y: 37.4979
        '400':
          description: 입력 데이터 오류
        '500':
          description: 서버 오류
    post:
      tags:
        - Bars
      summary: 바 등록
      security:
        - cookieAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                images:
                  type: string
                  format: binary
                  example: MSG_8031703352165894.png
                name:
                  type: string
                  example: 원식바1
                address:
                  type: string
                  example: 서울특별시 강남구1
                tel:
                  type: string
                  example: 02-1234-5678
                time:
                  type: string
                  example: 18:00 - 02:00
                x:
                  type: number
                  example: 127
                y:
                  type: number
                  example: 37.4979
      responses:
        '201':
          description: 바 등록 성공
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류
        '403':
          description: 접근 제한    	
        '409':
          description: 중복 오류
        '500':
          description: 서버 오류
  /bars/:id:
    get:
      tags:
        - Bars
      summary: 바 정보 조회
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 바 정보 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  name:
                    type: string
                  image:
                    type: string
                  address:
                    type: string
                  tel:
                    type: string
                  time:
                    type: string
                  x:
                    type: number
                  y:
                    type: number
                example:
                  _id: 658168a64b2f58b3b093d737
                  name: 원식바1
                  image: MSG_8031703352165894.png
                  address: 서울특별시 강남구1
                  tel: 02-1234-5678
                  time: 18:00 - 02:00
                  x: 127
                  y: 37.4979
        '400':
          description: 입력 데이터 오류
        '404':
          description: 요청한 리소스 찾을 수 없음
        '500':
          description: 서버 오류
    put:
      tags:
        - Bars
      summary: 바 정보 수정
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                newImageNames:
                  type: string
                address:
                  type: string
                tel:
                  type: string
                time:
                  type: string
                x:
                  type: number
                y:
                  type: number
      responses:
        '201':
          description: 바 수정 성공
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류
        '403':
          description: 접근 제한    	
        '404':
          description: 요청한 리소스 찾을 수 없음
        '409':
          description: 중복 오류
        '500':
          description: 서버 오류
    delete:
      tags:
        - Bars
      summary: 바 정보 삭제
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 바 정보 삭제 성공
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류
        '403':
          description: 접근 제한    	
        '404':
          description: 요청한 리소스 찾을 수 없음
        '500':
          description: 서버 오류
  /reviews/:id:
    put:
      tags:
        - Reviews
      summary: 리뷰 수정
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                newImageNames:
                  type: array
                  items:
                    type: string
                rating:
                  type: number
      responses:
        '200':
          description: 리뷰 수정 성공
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류
        '403':
          description: 접근 제한    	
        '404':
          description: 요청한 리소스 찾을 수 없음
        '409':
          description: 중복 오류
        '500':
          description: 서버 오류          
    delete:
      tags:
        - Reviews
      summary: 리뷰 삭제
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 리뷰 삭제 성공
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류
        '403':
          description: 접근 제한    	
        '404':
          description: 요청한 리소스 찾을 수 없음
        '500':
          description: 서버 오류          

  /reviews/:id/likes:
    post:
      tags:
        - Reviews
      summary: 리뷰 좋아요 추가
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: 리뷰 좋아요 추가 성공
    delete:
      tags:
        - Reviews
      summary: 리뷰 좋아요 삭제
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 리뷰 좋아요 삭제 성공
  /reviews/create/:id:
    post:
      tags:
        - Reviews
      summary: 리뷰 등록
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                newImageNames:
                  type: array
                  items:
                    type: string
                rating:
                  type: number
      responses:
        '201':
          description: 리뷰 등록 성공
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류
        '403':
          description: 접근 제한    	
        '409':
          description: 중복 오류
        '500':
          description: 서버 오류          
  /reviews/list:
    get:
      tags:
        - Reviews
      summary: 상품 리뷰 목록 조회
      parameters:
        - name: id
          in: query
          schema:
            type: string
        - name: perPage
          in: query
          schema:
            type: number
        - name: page
          in: query
          schema:
            type: number
        - name: cursorId
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 상품 리뷰 목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  email:
                    type: string
                  content:
                    type: string
                  images:
                    type: array
                    items:
                      type: string
                  likeCount:
                    type: number
                  createdAt:
                    type: string
                    format: date
        '400':
          description: 입력 데이터 오류 	
        '500':
          description: 서버 오류                    
  /reviews/users:
    get:
      tags:
        - Reviews
      summary: 유저의 리뷰 목록 조회
      security:
        - cookieAuth: []
      parameters:
        - name: type
          in: query
          schema:
            type: string
            enum: [cocktails, recipes]
        - name: perPage
          in: query
          schema:
            type: number
        - name: page
          in: query
          schema:
            type: number
        - name: cursorId
          in: query
          schema:
            type: string
        - name: cursorValue
          in: query
          schema:
            type: number
      responses:
        '200':
          description: 유저의 리뷰 목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  date:
                    type: string
                    format: date
                  list:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                        type:
                          type: string
                        name:
                          type: string
                        content:
                          type: string
                        images:
                          type: array
                          items:
                            type: string
                        createdAt:
                          type: string
                          format: date
        '400':
          description: 입력 데이터 오류
        '401':
          description: 인증 오류 	
        '500':
          description: 서버 오류                          
  /reviews/search:
    get:
      tags:
        - Reviews
      summary: 리뷰 검색 조회(관리자)
      security:
        - cookieAuth: []
      parameters:
        - name: keyword
          in: query
          schema:
            type: string
        - name: type
          in: query
          schema:
            type: string
            enum: [cocktails, recipes]
        - name: perPage
          in: query
          schema:
            type: number
        - name: page
          in: query
          schema:
            type: number
      responses:
        '200':
          description: 리뷰 검색 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  type:
                    type: string
                  name:
                    type: string
                  content:
                    type: string
                  images:
                    type: array
                    items:
                      type: string
                  createdAt:
                    type: string
                    format: date
        '400':
          description: 입력 데이터 오류
        '500':
          description: 서버 오류                    
  /search:
    get:
      tags:
        - Search
      summary: 칵테일, 레시피 검색
      parameters:
        - name: keyword
          in: query
          schema:
            type: string
          example: 진
        - name: type
          in: query
          schema:
            type: string
            enum: [cocktails, recipes]
            example: null
        - name: sort
          in: query
          schema:
            type: string
            enum: [rating, review]
            example: rating
        - name: cursorId
          in: query
          schema:
            type: string
          example: 6585064859ab0ce782365340
        - name: cursorValue
          in: query
          schema:
            type: number
          example: 5
        - name: perPage
          in: query
          schema:
            type: number
          example: 2
        - name: page
          in: query
          schema:
            type: number
      responses:
        '200':
          description: 검색 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                    example: 5
                  cocktailSize:
                    type: number
                    example: 3
                  diyRecipeSize:
                    type: number
                    example: 2
                  cocktails:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          example: 65828c5287834f1ddccc2c48
                        name:
                          type: string
                          example: 마가리타1
                        images:
                          type: string
                          example: /images/1703335018573.png
                        avgRating:
                          type: number
                          example: 3
                        reviewCount:
                          type: number
                          example: 4
                        createdAt:
                          type: string
                          format: date-time
                          example: 2023-12-20T06:40:18.375Z
                  diyRecipes:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          example: 658d74c23df0c5678e7d26b2
                        name:
                          type: string
                          example: 실버 불렛
                        images:
                          type: string
                          example: /images/diyRecipe_Silver Bullet_6431703769282840.jpg
                        avgRating:
                          type: number
                          example: 0
                        reviewCount:
                          type: number
                          example: 0
                        createdAt:
                          type: string
                          format: date-time
                          example: 2023-12-20T06:40:18.375Z
        '400':
          description: 입력 데이터 오류
        '500':
          description: 서버 오류                          
  /search/admin:
    get:
      tags:
        - Search
      summary: (관리자) 칵테일,레시피 검색
      parameters:
        - name: keyword
          in: query
          schema:
            type: string
            example: 마
        - name: type
          in: query
          schema:
            type: string
            enum: [cocktails, recipes]
            example: cocktails
        - name: perPage
          in: query
          schema:
            type: integer
            example: 3
        - name: page
          in: query
          schema:
            type: integer
            example: 1

      responses:
        '200':
          description: 검색 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  cocktailSize:
                    type: integer
                    example: 9
                  cocktails:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                        name:
                          type: string
                        createdAt:
                          type: string
                      example:
                        - _id: '6584f93e46ab6e13c78e53e7'
                          name: '마가리타8'
                          createdAt: '2023-12-22T02:49:30.375Z'
                        - _id: '6584f93646ab6e13c78e53e6'
                          name: '마가리타7'
                          createdAt: '2023-12-22T02:49:26.375Z'
                        - _id: '6584f92d46ab6e13c78e53e5'
                          name: '마가리타6'
                          createdAt: '2023-12-22T02:49:17.375Z'
        '400':
          description: 입력 데이터 오류
        '500':
          description: 서버 오류                          
  /search/auto-complete:
    get:
      tags:
        - Search
      summary: 검색 자동 완성
      parameters:
        - name: keyword
          in: query
          schema:
            type: string
            example: 마
        - name: perPage
          in: query
          schema:
            type: number
            example: 3
        - name: page
          in: query
          schema:
            type: number
            example: 1
      responses:
        '200':
          description: 검색 자동 완성 성공
          content:
            application/json:
              schema:
                type: array
                example:
                  - 마가리타1
                  - 마가리타2
                  - 마가리타3
                items:
                  type: string
                  properties:
                    name:
                      type: string
        '400':
          description: 입력 데이터 오류
        '500':
          description: 서버 오류